spring:
  profiles: set1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test1234
    url: jdbc:mariadb://springboot.ch7o54aitash.ap-northeast-2.rds.amazonaws.com:3306/springboot

server:
  port: 8082
