spring:
  profiles:
    active: local # 기본 환경 선택
    include: real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  tymeleaf:
    prefix: classpath:/templates/
    suffix: .html
custom:
  uploadPath: /Users/ktm/Desktop/jpa/src/main/resources/static/img

# local 환경
---
spring:
  spring.profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10MB
      location: Users/TEMP