spring:
  profiles:
    active: local # 기본 환경 선택
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10MB
      location: Users/TEMP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  tymeleaf:
    prefix: classpath:/templates/
    suffix: .html

custom:
  uploadPath: /home/ec2-user/img

---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---

#  h2:
#    console:
#      enabled: true
