spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10MB
      location: Users/TEMP

custom:
  uploadPath: /Users/ktm/Desktop/jpa/src/main/resources/static/img


# local 환경
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test1234
    url: jdbc:mariadb://springboot.ch7o54aitash.ap-northeast-2.rds.amazonaws.com:3306/springboot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
